# Generated by Django 4.0.5 on 2022-06-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv0', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeadModel',
        ),
    ]
