# Generated by Django 3.2 on 2022-07-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20220627_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='firma_name_sender',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='who_send',
            field=models.BooleanField(choices=[(True, 'O`zi aloqaga chiqan'), (False, 'Tashqi tashkilot orqali')], default=True),
        ),
    ]
